lshanguage: python
python:
  - "3.4"
env:
  - LANGUAGE_PAGES_VERSION="0.3.5"
script:
  - sh -x "./ci-build.sh"
before_deploy:
  - sh -x "./ci-pre-deploy.sh"
  - git config --local user.name "Travis CI"
  - git config --local user.email "$COMMIT_AUTHOR_EMAIL"

deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  overwrite: true
  on:
    tags: true
  skip_cleanup: true

