language: python
python:
  - "3.4"
env:
  - LANGUAGE_PAGES_VERSION="0.3.5"
script:
  - sh -x "./ci-build.sh"
before_deploy:
  - sh -x "./ci-pre-deploy.sh"
deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  file:
    - "lang_info_pages_${LANGUAGE_PAGES_VERSION}.tar.gz"
  overwrite: true
  on:
    tags: true
    all_branches: true
  skip_cleanup: true
