language: python
python:
  - "3.4"
env:
  - VERSION = "0.3.0"
  - TRAVIS_TAG = $VERSION
script: bash ./ci-deploy.sh
deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  file:
    - "language_info_pages.tar.gz"
  overwrite: true
  on:
    tags: true
    all_branches: true
  skip_cleanup: true
