language: python
python:
  - "3.4"
before_deploy:
  if ! [[ $TRAVIS_TAG ]]; then
    export TRAVIS_TAG="0.2.0.a4" &&
    git config --local user.name "$USER_NAME" &&
    git config --local user.email "$USER_EMAIL" &&
    git tag -a "$TRAVIS_TAG";
  fi
script: bash ./ci-deploy.sh
deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  file: ./language_info_pages.tar.gz
  overwrite: true
  tag_name: $TRAVIS_TAG
  on:
    tags: true
  skip_cleanup: true
