language: python
python:
  - "3.4"
before_deploy:
  if ! [[ $TRAVIS_TAG ]]; then
    export TRAVIS_TAG="0.2.0.a0" &&
    git config --local user.name "$USER_NAME" &&
    git config --local user.email "$USER_EMAIL" &&
    git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT";
  fi
script: bash ./ci-deploy.sh
deploy:
  provider: releases
  api_key: GITHUB_TOKEN
  file: ./language_info_pages.tar.gz
  overwrite: true
  tag_name: $TRAVIS_TAG
  on:
    tags: true
  skip_cleanup: true
