language: python
python:
  - "3.4"
before_deploy:
  - git config --local user.name "$USER_NAME" &&
  - git config --local user.email "$USER_EMAIL"
env:
  - TRAVIS_TAG = "0.3.0.a0"
deploy:
  script: bash ./ci-deploy.sh
  provider: releases
  github_token: $GITHUB_TOKEN
  file: ./language_info_pages.tar.gz
  overwrite: true
  tag_name: $TRAVIS_TAG
  on:
    tags: true
  skip_cleanup: true
