language: python
python:
  - "3.4"
env:
  - LANGUAGE_PAGES_VERSION="0.3.6"
script:
  - sh -x "./ci-build.sh"
before_deploy:
  - sh -x "./ci-pre-deploy.sh"
  - git config --local user.name "Travis CI"
  - git config --local user.email "$COMMIT_AUTHOR_EMAIL"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "lang_info_pages_${LANGUAGE_PAGES_VERSION}.tar.gz"
  overwrite: true
  on:
    tags: true
  skip_cleanup: true

