language: python
python:
  - "3.4"
env:
  - LANGUAGE_PAGES="0.3.5"
script:
  - sh -c "./ci-deploy.sh"
deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  file:
    - "language_info_pages.tar.gz"
  overwrite: true
  on:
    tags: true
    all_branches: true
  skip_cleanup: true
